name: PUtility
version: '${project.version}'
main: com.pallux.putility.PUtility
api-version: '1.21'
authors: [ Pallux ]
description: A utility plugin with toggleable features.
depend: [ Vault ]
softdepend: [ PlaceholderAPI, PlayerPoints ]

commands:
  shop:
    description: Opens the shop GUI.
    usage: /shop
    permission: pu.shop
  hide:
    description: Toggle name scrambling.
    usage: /hide
    permission: pu.hide
  putility:
    description: Main admin command.
    usage: /putility <reload>
    permission: pu.admin
    aliases: [ pu ]

permissions:
  pu.shop:
    description: Allows opening the shop.
    default: true
  pu.hide:
    description: Allows using /hide.
    default: false
  pu.admin:
    description: Admin access to PUtility.
    default: op
