name: PUtility
version: '${project.version}'
main: com.pallux.putility.PUtility
api-version: '1.21'
authors: [ Pallux ]
description: Vaaaaarious utilities I use for Setups
depend: [ Vault ]
softdepend: [ PlaceholderAPI, PlayerPoints ]

commands:
  shop:
    description: Opens the shop GUI.
    usage: /shop
    permission: pu.shop
  putility:
    description: Main admin command.
    usage: /putility <reload>
    permission: pu.admin
    aliases: [ pu ]

permissions:
  pu.shop:
    description: Allows opening the shop.
    default: true
  pu.admin:
    description: Admin access to PUtility.
    default: op
